hard_tabs = true
max_width = 999999999 ## Kindly twitch less when things change line length.
merge_derives = false
# struct_lit_single_line doesn't have a 'preserve' option and i'm mad.
# use_small_heuristics is interesting but vague

# unstable_features = true ## requires the nightly version of the fmt tool, which is trouble.
# overflow_delimited_expr = true ## unstable
# blank_lines_upper_bound = 3 ## unstable
# enum_discrim_align_threshold = 20 ## unstable
# struct_field_align_threshold = 40 ## unstable
